app/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from courses.views import CourseListView


urlpatterns = [
    path('accounts/login/', auth_views.LoginView.as_view(success_url=reverse_lazy('course_list')), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('course/', include('courses.urls')),
    path('', CourseListView.as_view(), name='course_list'),
    path('students/', include('students.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('api/', include('courses.api.urls', namespace='api')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

app/students/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page


app_name = 'students'
urlpatterns = [
    path('register/', views.StudentRegistrationForm.as_view(), name='student_registration'),
    path('enroll-course/', views.StudentEnrollCourseView.as_view(), name='student_enroll_course'),
    path(
        'courses/',
        views.StudentCourseListView.as_view(),
        name='student_course_list'
    ),
    path(
        'course/<int:pk>/',
        cache_page(60*15)(views.StudentCourseDetailView.as_view()),
        name='student_course_detail'
    ),
    path(
        'course/<pk>/<modules_id>/',
        cache_page(60*15)(views.StudentCourseDetailView.as_view()),
        name='student_course_detail_module'
    ),
]

app/students/models.py
from django.db import models

app/students/forms.py
from django import forms
from courses.models import Course


class CourseEnrollForm(forms.Form):
    course = forms.ModelChoiceField(queryset=Course.objects.none(), widget=forms.HiddenInput)

    def __init__(self, *args, **kwargs):
        super(CourseEnrollForm, self).__init__(*args, **kwargs)
        self.fields['course'].queryset = Course.objects.all()

app/students/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormView
from .forms import CourseEnrollForm
from django.views.generic.list import ListView
from courses.models import Course


class StudentRegistrationForm(CreateView):
    template_name = 'students/student/registration.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('students:student_course_list')

    def form_valid(self, form):
        result = super().form_valid(form)
        cd = form.cleaned_data
        user = authenticate(username=cd['username'], password=cd['password1'])
        login(self.request, user)
        return result


class StudentEnrollCourseView(LoginRequiredMixin, FormView):
    course = None
    form_class = CourseEnrollForm

    def form_valid(self, form):
        self.course = form.cleaned_data['course']
        self.course.student.add(self.request.user)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('students:student_course_detail', args=(self.course.id,))


class StudentCourseListView(LoginRequiredMixin, ListView):
    model = Course
    template_name = 'students/course/list.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(student__in=[self.request.user])


class StudentCourseDetailView(LoginRequiredMixin, DetailView):
    model = Course
    template_name = 'students/course/detail.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(student__in=[self.request.user])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        course = self.get_object()
        print(self.kwargs)
        if 'modules_id' in self.kwargs:
            context['module'] = course.modules.get(
                id=self.kwargs['modules_id']
            )
        else:
            context['module'] = course.modules.all()[0]
        return context

app/students/templates/students/course/detail.html
{% extends 'base.html' %}
{% load cache %}
{% block title %}
	{{ object.title }}
{% endblock %}
{% block body %}
	<h1>{{ module.title }}</h1>
    <div class="contents">
        <h3>Modules</h3>
        <ul>
            {% cache 600 module_contents module %}
            {% for m in object.modules.all %}
            	<li data-id="{{ m.id }}">
                    <a href="{% url 'students:student_course_detail_module' object.id m.id %}">
                        <span>
                            Module <span>{{ m.order|add:1 }}</span>
                        </span>
                        <br>
                        {{ m.title }}1
                    </a>
                </li>
            {% empty %}
                <li>No modules yet</li>
            {% endfor %}
            {% endcache %}
        </ul>
    </div>
    <div class="module">
    {{ module.description }}
        {% for content in module.contents.all %}
            {% with item=content.item %}
            	<h2>{{ item.title }}</h2>
                {{ item.render }}
            {% endwith %}
        {% endfor %}
    </div>
{% endblock %}

app/students/templates/students/course/list.html
{% extends 'base.html' %}
{% block  title %}
	My courses
{% endblock %}
{% block body %}
	<h1>My courses</h1>
    <div class="module">
        {% for course in object_list %}
        	<div class="course-info">
                <h3>{{ course.title }}</h3>
                <p><a href="{% url 'students:student_course_detail' course.id %}" >Access Contents</a></p>
            </div>
        {% empty %}
            <p>
                You have not enrolled any courses yet
                <a href="{% url 'course_list' %}">Browse courses</a>
                to enroll in course
            </p>
        {% endfor %}
        
    </div>
{% endblock %}